spring:
  profiles:
    active: development
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:~/test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    validationQuery: SELECT 1
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  thymeleaf:
    mode: LEGACYHTML5
logging:
  config: classpath:log4j.properties
server:
  tomcat:
    basedir: target/tomcat